### ISSUE TITLE
将原cqitca的静态网页迁移到index.html

### ISSUE THREAD

**Issue by ganziqim** [NiX-Team/nix-team.github.io#1]
后续博客相关应该都是放GitHubPages上管理比较方便些，具体的规划我再想想，暂时先把目前能用到的迁移过来

**Comment by GLBB** [comment]
收到

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by MadratJerry** [comment]
Reopen in [NiX Blog](https://github.com/NiX-Team/NiX/issues/1)
